- name: Crear usuario devops
  user:
    name: devops
    groups: sudo
    shell: /bin/bash
    state: present
    create_home: true

- name: Agregar clave pública SSH para devops
  authorized_key:
    user: devops
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  when: lookup('file', '~/.ssh/id_rsa.pub', errors='ignore') is defined

